spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://124.220.184.6:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: pys564335

logging:
  level:
    root: info
    com.pys: debug
  file: log/blog-dev.log
server:
  port: 8080