spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://124.220.184.6:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: pys564335
comment.avatar: /images/avatar.png
message.avatar: /images/avatar.png

mybatis:
  type-aliases-package: com.pys.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  #  dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
